// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'create_direct_model.g.dart';

@JsonSerializable()
class CreateDirectModel {
  final String id;
  final String userId;
  final String title;
  final String? directImage;

  CreateDirectModel({
    required this.id,
    required this.title,
    required this.userId,
    required this.directImage,
  });

  factory CreateDirectModel.fromJson(Map<String, dynamic> json) =>
      _$CreateDirectModelFromJson(json);

  Map<String, dynamic> toJson() => _$CreateDirectModelToJson(this);
}
