// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'direct_message_model.g.dart';

@JsonSerializable()
class DirectMessageModel {
  final String directMessageId;
  final String directMessage;
  final String sended;
  final String senderId;
  final String senderName;
  final List<DirectFile> directFiles;

  DirectMessageModel({
    required this.directMessageId,
    required this.directMessage,
    required this.sended,
    required this.senderId,
    required this.senderName,
    required this.directFiles,
  });

  factory DirectMessageModel.fromJson(Map<String, dynamic> json) =>
      _$DirectMessageModelFromJson(json);

  Map<String, dynamic> toJson() => _$DirectMessageModelToJson(this);
}

@JsonSerializable()
class DirectFile {
  final String link;

  DirectFile({
    required this.link,
  });

  factory DirectFile.fromJson(Map<String, dynamic> json) =>
      _$DirectFileFromJson(json);

  Map<String, dynamic> toJson() => _$DirectFileToJson(this);
}
