// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'post_model_response.g.dart';

@JsonSerializable()
class PostModelResponse {
  final String? id;
  final String? created;
  final String? text;
  final String? authorId;
  final List<PostFile>? postFiles;
  final String? authorAvatar;
  final int? commentAmount;
  final int? likesAmount;

  PostModelResponse({
    required this.id,
    required this.created,
    required this.text,
    required this.authorId,
    required this.postFiles,
    required this.authorAvatar,
    required this.commentAmount,
    required this.likesAmount,
  });

  factory PostModelResponse.fromJson(Map<String, dynamic> json) =>
      _$PostModelResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostModelResponseToJson(this);
}

@JsonSerializable()
class PostFile {
  final String? link;

  PostFile({
    required this.link,
  });

  factory PostFile.fromJson(Map<String, dynamic> json) =>
      _$PostFileFromJson(json);

  Map<String, dynamic> toJson() => _$PostFileToJson(this);
}
