// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'send_push_model.g.dart';

@JsonSerializable()
class SendPushModel {
  final String? userId;
  final Push push;

  SendPushModel({
    this.userId,
    required this.push,
  });

  factory SendPushModel.fromJson(Map<String, dynamic> json) =>
      _$SendPushModelFromJson(json);

  Map<String, dynamic> toJson() => _$SendPushModelToJson(this);
}

@JsonSerializable()
class Push {
  final int? badge;
  final String? sound;
  final Alert alert;
  final CustomData customData;

  Push({
    this.badge,
    this.sound,
    required this.alert,
    required this.customData,
  });

  factory Push.fromJson(Map<String, dynamic> json) => _$PushFromJson(json);

  Map<String, dynamic> toJson() => _$PushToJson(this);
}

@JsonSerializable()
class Alert {
  final String? title;
  final String? subtitle;
  final String? body;

  Alert({
    this.title,
    this.subtitle,
    this.body,
  });

  factory Alert.fromJson(Map<String, dynamic> json) => _$AlertFromJson(json);

  Map<String, dynamic> toJson() => _$AlertToJson(this);
}

@JsonSerializable()
class CustomData {
  final String additionalProp1;
  final String additionalProp2;
  final String additionalProp3;

  CustomData({
    required this.additionalProp1,
    required this.additionalProp2,
    required this.additionalProp3,
  });

  factory CustomData.fromJson(Map<String, dynamic> json) =>
      _$CustomDataFromJson(json);

  Map<String, dynamic> toJson() => _$CustomDataToJson(this);
}
